name: Main CI

on:
  push:
    branches:
      - 'main'
      - 'release-**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '285.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Build
      run: make local

    - name: Test
      run: make test


    # Only try to publish the container image from the root repo; forks don't have permission to do so and will always get failures.
    - name: Publish container image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        BIN=velero
        RESTORE_HELPER_BIN=velero-restore-helper
        VERSION=$(./hack/docker-push.sh | grep 'VERSION:' | awk -F: '{print $2}' | xargs)

        # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
        source hack/ci/build_util.sh

        GS_BUCKET=velero-builds
        VELERO_IMAGE=${BIN}-${VERSION}
        VELERO_RESTORE_HELPER_IMAGE=${RESTORE_HELPER_BIN}-${VERSION}
        VELERO_IMAGE_FILE=${VELERO_IMAGE}.tar.gz
        VELERO_RESTORE_HELPER_IMAGE_FILE=${VELERO_RESTORE_HELPER_IMAGE}.tar.gz
        VELERO_IMAGE_BACKUP_FILE=${VELERO_IMAGE}-'build.'${GITHUB_RUN_NUMBER}.tar.gz
        VELERO_RESTORE_HELPER_IMAGE_BACKUP_FILE=${VELERO_RESTORE_HELPER_IMAGE}-'build.'${GITHUB_RUN_NUMBER}.tar.gz

        cp ${VELERO_IMAGE_FILE} ${VELERO_IMAGE_BACKUP_FILE}
        cp ${VELERO_RESTORE_HELPER_IMAGE_FILE} ${VELERO_RESTORE_HELPER_IMAGE_BACKUP_FILE}

        uploader ${VELERO_IMAGE_FILE} ${GS_BUCKET}
        uploader ${VELERO_RESTORE_HELPER_IMAGE_FILE} ${GS_BUCKET}
        uploader ${VELERO_IMAGE_BACKUP_FILE} ${GS_BUCKET}
        uploader ${VELERO_RESTORE_HELPER_IMAGE_BACKUP_FILE} ${GS_BUCKET}