name: Main CI

on:
  push:
    branches:
      - 'main'
      - 'release-**'
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '285.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Build
      run: make local

    - name: Test
      run: make test


    # Only try to publish the container image from the root repo; forks don't have permission to do so and will always get failures.
    - name: Publish container image
      if: github.repository == 'vmware-tanzu/velero'
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        ./hack/docker-push.sh

    # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
    - name: Publish container image to GCP
      run: |
        source hack/ci/build_util.sh
        VELERO_IMAGE=velero-main
        VELERO_RESTORE_HELPER_IMAGE=velero-restore-helper-main
        cp $VELERO_IMAGE $VELERO_IMAGE-'build.'$GITHUB_RUN_NUMBER
        cp $VELERO_RESTORE_HELPER_IMAGE $VELERO_RESTORE_HELPER_IMAGE-'build.'$GITHUB_RUN_NUMBER
        uploader  ${VELERO_IMAGE}.tar.gz velero-builds
        uploader  ${VELERO_RESTORE_HELPER_IMAGE}.tar.gz velero-builds
        uploader  ${VELERO_IMAGE}-'build.'$GITHUB_RUN_NUMBER.tar.gz velero-builds
        uploader  ${VELERO_RESTORE_HELPER_IMAGE}-'build.'$GITHUB_RUN_NUMBER.tar.gz velero-builds